---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:

          - id: black
            name: Format with Black
            entry: black
            language: system
            types: [python]

          - id: ruff
            name: Check with Ruff
            entry: ruff check
            language: system
            pass_filenames: false
            always_run: true
            args: ["."]

          - id: mypy
            name: Validate types with MyPy
            entry: mypy
            language: system
            types: [python]
            pass_filenames: false
            args:
              - "."
